//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enquete.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class option
    {
        public short option_id { get; set; }
        public string option_description { get; set; }
        public long poll_id { get; set; }
        public short qty { get; set; }
    
        public virtual poll poll { get; set; }
    }
}
